spring:
  application:
    name: oauth-basic-demo

  security:
    oauth2:
      client:
        registration:
          # Google OAuth ??
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          # Github OAuth ??
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope:
              - user:email
              - read:user

# ?? ??
logging:
  level:
    org.springframework.security: DEBUG
    com.example.oauth: DEBUG

# ?? ??
server:
  port: 8080