spring:
  application:
    name: oauth-basic-demo

  security:
    oauth2:
      client:
        registration:
          # Google OAuth ??
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          # Github OAuth ??
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope:
              - user:email
              - read:user

# ?? ??
logging:
  level:
    org.springframework.security: DEBUG
    com.example.oauth: DEBUG

# ?? ??
server:
  port: 8080